config/routes.rb
Rails.application.routes.draw do
  resources :corgis
  devise_for :users

  root 'corgis#index'

end

app/models/corgi.rb
class Corgi < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :corgis
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/corgis_controller.rb
class CorgisController < ApplicationController
  before_action :authenticate_user!
  before_action :set_corgi, only: [:show, :edit, :update, :destroy]

  # GET /corgis
  # GET /corgis.json
  def index
    @corgis = Corgi.all
  end

  # GET /corgis/1
  # GET /corgis/1.json
  def show
  end

  # GET /corgis/new
  def new
    @corgi = Corgi.new
  end

  # GET /corgis/1/edit
  def edit
  end

  # POST /corgis
  # POST /corgis.json
  def create
    @corgi = Corgi.new(corgi_params)

    respond_to do |format|
      if @corgi.save
        format.html { redirect_to @corgi, notice: 'Corgi was successfully created.' }
        format.json { render :show, status: :created, location: @corgi }
      else
        format.html { render :new }
        format.json { render json: @corgi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corgis/1
  # PATCH/PUT /corgis/1.json
  def update
    respond_to do |format|
      if @corgi.update(corgi_params)
        format.html { redirect_to @corgi, notice: 'Corgi was successfully updated.' }
        format.json { render :show, status: :ok, location: @corgi }
      else
        format.html { render :edit }
        format.json { render json: @corgi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corgis/1
  # DELETE /corgis/1.json
  def destroy
    @corgi.destroy
    respond_to do |format|
      format.html { redirect_to corgis_url, notice: 'Corgi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corgi
      @corgi = Corgi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corgi_params
      params.require(:corgi).permit(:name, :age, :user_id, :filename)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corgis_helper.rb
module CorgisHelper
end

app/views/corgis/_form.html.erb
<%= form_for(@corgi) do |f| %>
  <% if @corgi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corgi.errors.count, "error") %> prohibited this corgi from being saved:</h2>

      <ul>
      <% @corgi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <select name="corgi[filename]">
      <option>1.jpeg</option>
      <option>2.jpeg</option>
      <option>3.jpeg</option>
      <option>4.jpeg</option>
      <option>5.jpeg</option>
    </select>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/corgis/edit.html.erb
<h1>Editing Corgi</h1>

<%= render 'form' %>

<%= link_to 'Show', @corgi %> |
<%= link_to 'Back', corgis_path %>

app/views/corgis/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
<h1>Listing Corgis</h1>
<p>Hello <%= current_user.email %>!</p>
</div>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Age</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @corgis.each do |corgi| %>
      <tr>
        <td><%= link_to(image_tag(corgi.filename, class: "image" ), corgi) %></td>
        <td><%= corgi.name %></td>
        <td><%= corgi.age %></td>
        <td><%= corgi.user.email %></td>
        <td class="actions btn btn-primary"><%= link_to 'Show', corgi %></td>
        <td class="actions btn btn-success"><%= link_to 'Edit', edit_corgi_path(corgi) %></td>
        <td class="actions btn btn-danger"><%= link_to 'Destroy', corgi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Corgi', new_corgi_path %>
<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>

app/views/corgis/new.html.erb
<h1>New Corgi</h1>

<%= render 'form' %>

<%= link_to 'Back', corgis_path %>

app/views/corgis/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@corgi.filename, class: "image" )%>

<p>
  <strong>Name:</strong>
  <%= @corgi.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @corgi.age %>
</p>

<p>
  <strong>User:</strong>
  <%= @corgi.user.email %>
</p>
<p>
  <strong>Filename</strong>
  <%=@corgi.filename%>
</p>

<%= link_to 'Edit', edit_corgi_path(@corgi) %> |
<%= link_to 'Back', corgis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Okcorgi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://bootswatch.com/cosmo/bootstrap.min.css">
</style>
</head>
<body>

  <header>
  <%= image_tag '1.jpeg' %><%= image_tag '1.jpeg' %><%= image_tag '1.jpeg' %><%= image_tag '1.jpeg' %><%= image_tag '1.jpeg' %>
  <%= image_tag '1.jpeg' %>


  </header>

<%= yield %>

</body>
</html>